--DAY 2 Tasks

--Retrieve all columns from the customer table.
SELECT *
FROM customer;
 
--Display only film_id, title, and rating from the film table.
SELECT film_id, title, rating
FROM film;

--Retrieve the first 15 records from the actor table.
SELECT *
FROM actor
LIMIT 15;

--Retrieve all customers and sort them by last_name in ascending order.
SELECT *
FROM customer
ORDER BY last_name desc;

--Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.
SELECT payment_id, customer_id, amount
FROM payment
ORDER BY amount asc;

--Retrieve customers sorted by: first_name in ascending order & last_name in descending order
SELECT first_name, last_name
FROM customer
ORDER BY first_name asc, last_name desc;

--Retrieve all payments where the amount is greater than 5.
SELECT payment_id, amount
FROM payment
WHERE amount > 5.0
ORDER BY amount;

--Retrieve all payments where the amount is between 3.99 and 6.99.
SELECT payment_id, amount
FROM payment
WHERE amount BETWEEN 3.99 AND 6.99
ORDER BY amount;

--Retrieve all customers whose first_name starts with the letter J.
SELECT *
FROM customer
WHERE first_name LIKE 'J%'
ORDER BY first_name;

--Retrieve all films where the description contains the word “Action”.
SELECT *
FROM film
WHERE description LIKE '%Action%'
ORDER BY title;

--Retrieve payments greater than 7, sorted by amount in descending order.
SELECT *
FROM payment
WHERE amount > 7.0
ORDER BY amount desc;

--Retrieve customers whose first name ends with “n”, sorted alphabetically.
SELECT *
FROM customer
WHERE first_name LIKE '%n'
ORDER BY first_name asc;

--Calculate the total amount spent by each customer.
SELECT customer_id, SUM(amount) AS total_amount
FROM payment
GROUP BY customer_id
ORDER BY total_amount;

--Retrieve the average payment amount per customer.
SELECT customer_id, round(AVG(amount),2) AS avg_amount
FROM payment
GROUP BY customer_id
ORDER BY avg_amount;

--Calculate the total revenue generated by each staff member.
SELECT staff_id, SUM(amount) AS total_revenue
FROM payment
GROUP BY staff_id
ORDER BY total_revenue;

--Identify the top 5 customers based on total payment amount.
SELECT customer_id, SUM(amount) AS total_amount
FROM payment
GROUP BY customer_id
ORDER BY total_amount desc;

--Find the average film length per release year.
SELECT film_id, round(AVG(length),2) AS avg_film_length, release_year
FROM film
GROUP BY film_id 
ORDER BY release_year;

--Retrieve the highest single payment amount in the payment table.
SELECT customer_id, SUM(amount) AS total_amount
FROM payment
GROUP BY customer_id
ORDER BY total_amount desc 
FETCH FIRST ROW ONLY;

--Count how many payments each customer has made.
SELECT customer_id, COUNT(amount) AS nos_of_payments
FROM payment
GROUP BY customer_id
ORDER BY nos_of_payments desc;

--Retrieve customers who are active and sort them by first_name.
SELECT *
FROM customer
WHERE active = '1'
ORDER BY first_name;
